# **NumPy Documentation**

## **1. Introduction to NumPy:**

NumPy (Numerical Python) is a powerful library for numerical computations in Python. It provides support for multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

Key Features:

    - Multi-dimensional array support (`ndarray`)
    - Fast mathematical operations
    - Broadcasting for vectorized   operations
    - Integration with C/C++ and Fortran for high-performance computations

## **2. Installation:**

To install NumPy, use the following command:

In [1]:
pip install numpy

The `np` alias is a standard convention in the Python community.

## **3. Importing NumPy (`ndarray`):**

#### **Creating Arrays:**

You can create NumPy arrays using `np.array().`

Example:

In [3]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3])
print(arr1)  # Output: [1 2 3]

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


#### **Array Attributes:**

Common attributes of `ndarray`:

    shape: Returns the dimensions of the array
    ndim: Returns the number of dimensions
    dtype: Data type of the array elements
    size: Number of elements in the array

Example:

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Data type:", arr.dtype)  # Output: int64 (or int32 on some systems)
print("Size:", arr.size)  # Output: 6

Shape: (2, 3)
Number of dimensions: 2
Data type: int64
Size: 6


## **4. Array Initialization Methods:**

NumPy provides several functions to create arrays with predefined values.
#### **4.1. `np.zeros()`:**

Creates an array of zeros.

In [5]:
zeros_array = np.zeros((2, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


#### **4.2. `np.ones()`:**

Creates an array of ones.

In [6]:
ones_array = np.ones((3, 3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### **4.3. `np.eye()`:**

Creates an identity matrix.

In [7]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### **4.4. `np.arange()`:**

Creates an array with a range of values.

In [8]:
range_array = np.arange(0, 10, 2)  # Start at 0, end at 10, step by 2
print(range_array)  # Output: [0 2 4 6 8]

[0 2 4 6 8]


## **5. Array Indexing and Slicing:**
#### **Indexing:**

Access elements in an array using square brackets `[]`.

In [9]:
arr = np.array([10, 20, 30, 40])
print(arr[1])  # Output: 20

20


#### **Slicing:**

Extract a portion of the array.

In [10]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # Output: [20 30 40]

[20 30 40]


#### **Indexing in Multi-dimensional Arrays:**

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 2])  # Output: 6

6


## **6. Array Operations:**
#### **Element-wise Operations:**

In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print(arr1 + arr2)  # Output: [5 7 9]

# Multiplication
print(arr1 * arr2)  # Output: [ 4 10 18]

[5 7 9]
[ 4 10 18]


#### **Broadcasting:**

NumPy allows operations on arrays of different shapes through broadcasting.

In [13]:
arr = np.array([1, 2, 3])
print(arr + 5)  # Output: [6 7 8]

[6 7 8]


## **7. Mathematical Functions:**
#### **7.1. `np.sum()`:**

Computes the sum of elements.

In [14]:
arr = np.array([1, 2, 3, 4])
print(np.sum(arr))  # Output: 10

10


#### **7.2. `np.mean()`:

Computes the mean (average) of elements.

In [15]:
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))  # Output: 2.5

2.5


#### **7.3. `np.max()` and `np.min()`:**

Finds the maximum and minimum values.

In [16]:
arr = np.array([1, 2, 3, 4])
print(np.max(arr))  # Output: 4
print(np.min(arr))  # Output: 1

4
1


## **8. Reshaping Arrays:**
`np.reshape()`

Change the shape of an array.

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


## **9. Random Number Generation:**

NumPy provides several functions to generate random numbers.

`np.random.rand()`:

Generates random values between 0 and 1.

In [18]:
random_array = np.random.rand(3, 3)
print(random_array)

[[0.15851058 0.77840476 0.34719142]
 [0.51134158 0.36217371 0.95096118]
 [0.87167579 0.0574698  0.44772025]]


`np.random.randint()`:

Generates random integers within a specified range.

In [19]:
random_int_array = np.random.randint(1, 10, (2, 3))
print(random_int_array)

[[7 6 4]
 [7 8 6]]


## **10. Linear Algebra with NumPy:**
Matrix Multiplication (`np.dot()`)

In [20]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


## **11. Saving and Loading Data:**
**Saving Arrays:**

In [21]:
arr = np.array([1, 2, 3])
np.save('array.npy', arr)

**Loading Arrays:**

In [22]:
loaded_arr = np.load('array.npy')
print(loaded_arr)

[1 2 3]
